
/**************************************************************
 *	
 *	s_background, 8 bit, 11025Hz,
 *	1 channel, 155702 bytes/channel
 *	Total Size: 1 * 155702 + 4 (header) = 155746 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Documents and Settings\Administrator\Desktop\wav2c\s_background.wav
 *	Time-stamp: Wed Oct 28 00:27:50 2009
 *	
 **************************************************************/

#ifndef __S_BACKGROUNDH__
#define __S_BACKGROUNDH__

#define S_BACKGROUNDFREQ 11025
#define S_BACKGROUNDLEN 155702

extern const unsigned char s_background[155702];

#endif /* __S_BACKGROUNDH__ */
