
/**************************************************************
 *	
 *	s_machinegun, 8 bit, 11025Hz,
 *	1 channel, 3315 bytes/channel
 *	Total Size: 1 * 3315 + 4 (header) = 3359 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Documents and Settings\Administrator\Desktop\wav2c\s_machinegun.wav
 *	Time-stamp: Tue Oct 27 21:31:40 2009
 *	
 **************************************************************/

#ifndef __S_MACHINEGUNH__
#define __S_MACHINEGUNH__

#define S_MACHINEGUNFREQ 11025
#define S_MACHINEGUNLEN 3315

extern const unsigned char s_machinegun[3315];

#endif /* __S_MACHINEGUNH__ */
