
/**************************************************************
 *	
 *	s_ravenx, 8 bit, 11025Hz,
 *	1 channel, 12420 bytes/channel
 *	Total Size: 1 * 12420 + 4 (header) = 12464 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Documents and Settings\Administrator\Desktop\wav2c\s_ravenx.wav
 *	Time-stamp: Sun Nov 22 18:25:32 2009
 *	
 **************************************************************/

#ifndef __S_RAVENXH__
#define __S_RAVENXH__

#define S_RAVENXFREQ 11025
#define S_RAVENXLEN 12420

extern const unsigned char s_ravenx[12420];

#endif /* __S_RAVENXH__ */
