
/**************************************************************
 *	
 *	s_explosion, 8 bit, 11025Hz,
 *	1 channel, 6617 bytes/channel
 *	Total Size: 1 * 6617 + 4 (header) = 6661 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Documents and Settings\Administrator\Desktop\wav2c\s_explosion.wav
 *	Time-stamp: Sun Nov 22 18:25:39 2009
 *	
 **************************************************************/

#ifndef __S_EXPLOSIONH__
#define __S_EXPLOSIONH__

#define S_EXPLOSIONFREQ 11025
#define S_EXPLOSIONLEN 6617

extern const unsigned char s_explosion[6617];

#endif /* __S_EXPLOSIONH__ */
