
/**************************************************************
 *	
 *	s_longexpl, 8 bit, 11025Hz,
 *	1 channel, 38633 bytes/channel
 *	Total Size: 1 * 38633 + 4 (header) = 38677 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Documents and Settings\Administrator\Desktop\wav2c\s_longexpl.wav
 *	Time-stamp: Mon Nov 23 18:54:22 2009
 *	
 **************************************************************/

#ifndef __S_LONGEXPLH__
#define __S_LONGEXPLH__

#define S_LONGEXPLFREQ 11025
#define S_LONGEXPLLEN 38633

extern const unsigned char s_longexpl[38633];

#endif /* __S_LONGEXPLH__ */
