
/**************************************************************
 *	
 *	s_synth, 8 bit, 11025Hz,
 *	1 channel, 7226 bytes/channel
 *	Total Size: 1 * 7226 + 4 (header) = 7270 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Documents and Settings\Administrator\Desktop\wav2c\s_synth.wav
 *	Time-stamp: Wed Nov 11 02:53:38 2009
 *	
 **************************************************************/

#ifndef __S_SYNTHH__
#define __S_SYNTHH__

#define S_SYNTHFREQ 11025
#define S_SYNTHLEN 7226

extern const unsigned char s_synth[7226];

#endif /* __S_SYNTHH__ */
